param(
    [string]$ClassFile = "JavaHelper/out/com/lunarcookies/SessionSwitcher.class",
    [string]$OutFile = "Bridge/session_helper_bytes.inc"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
if (-not $root) { $root = (Get-Location).Path }

$classPath = Join-Path $root $ClassFile
$outPath = Join-Path $root $OutFile

if (-not (Test-Path $classPath)) {
    throw "Class file not found: $classPath"
}

$bytes = [System.IO.File]::ReadAllBytes($classPath)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Auto-generated by Embed-ClassBytes.ps1 - do not edit")
[void]$sb.AppendLine("static const unsigned char kSessionSwitcherClassBytes[] = {")

for ($i = 0; $i -lt $bytes.Length; $i++) {
    if ($i % 12 -eq 0) { [void]$sb.Append("    ") }
    [void]$sb.AppendFormat("0x{0:X2}", $bytes[$i])
    if ($i -lt $bytes.Length - 1) { [void]$sb.Append(",") }
    if ($i % 12 -eq 11) { [void]$sb.AppendLine() }
    elseif ($i -lt $bytes.Length - 1) { [void]$sb.Append(" ") }
}
if (($bytes.Length % 12) -ne 0) { [void]$sb.AppendLine() }
[void]$sb.AppendLine("};")
$lenLine = "static const unsigned int kSessionSwitcherClassLen = " + $bytes.Length + ";"
[void]$sb.AppendLine($lenLine)

$dir = Split-Path $outPath -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
[System.IO.File]::WriteAllText($outPath, $sb.ToString())
Write-Host ("Wrote {0} bytes to {1}" -f $bytes.Length, $outPath)
